In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read Summer Csv
summer_ml_file = pd.read_csv('summer_ML_final.csv')
summer_ml_file

,Year,season,country,noc,population,gdpperc,athlete_share,host,country_medal_total,medal_share_predicted,positive_medal_share,predicted_medals,Difference_Acutal_Predicted,latitude,longitude
0,2016,summer,Bolivia,BOL,11031800,6355.0,0.001225,0,0,-0.002457,0.000000,0.000000,0.000000,-17.056870,-64.991229
1,2016,summer,Finland,FIN,5495300,37239.0,0.006430,0,1,0.003392,0.003392,3.246085,-2.246085,63.246778,25.920916
2,2016,summer,South Africa,RSA,56207600,12139.0,0.010308,0,10,0.011354,0.011354,10.865334,-0.865334,-28.816624,24.991639
3,2016,summer,Dominica,DMA,71307,9550.0,0.000204,0,0,-0.004325,0.000000,0.000000,0.000000,19.097403,-70.302803
4,2016,summer,Ukraine,UKR,45004700,9214.0,0.023576,0,11,0.030684,0.030684,29.364808,-18.364808,49.487197,31.271832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,2016,summer,Malawi,MAW,17205300,1112.0,0.000510,0,0,-0.003104,0.000000,0.000000,0.000000,-13.268720,33.930196
157,2016,summer,Spain,ESP,46484100,30110.0,0.024087,0,17,0.030340,0.030340,29.035165,-12.035165,39.326234,-4.838065
158,2016,summer,Tunisia,TUN,11303900,11073.0,0.005103,0,3,0.002962,0.002962,2.834918,0.165082,33.843941,9.400138
159,2016,summer,Kenya,KEN,49051500,3169.0,0.005920,0,13,0.005287,0.005287,5.059780,7.940220,1.441968,38.431398
160,2016,summer,Madagascar,MAD,24894400,1381.0,0.000612,0,0,-0.002825,0.000000,0.000000,0.000000,-18.924960,46.441642

In [3]:
# Read Summer Csv
winter_ml_file = pd.read_csv('Winter_ML_final.csv')
winter_ml_file

,Unnamed: 0,year,season,Country,noc,population,gdpperc,athlete_share,host,country_medal_total,medal_share_predicted,positive_medal_share,predicted_medals,Difference_Actual_Predicted,Latitude,Longitude
0,0,2014,Winter,Canada,CAN,3.543740e+07,43607.0,0.068274,0,25.0,0.084995,0.084995,24.988571,0.011429,61.066692,-107.991707
1,1,2014,Winter,Azerbaijan,AZE,9.535080e+06,17439.0,0.001084,0,0.0,-0.002295,0.000000,0.000000,0.000000,40.393629,47.787251
2,2,2014,Winter,Iceland,ISL,3.273860e+05,38563.0,0.002980,0,0.0,0.010063,0.010063,2.958636,-2.958636,64.984182,-18.105901
3,3,2014,Winter,Paraguay,PAR,6.599520e+06,8382.0,0.000271,0,0.0,-0.007571,0.000000,0.000000,0.000000,-23.316593,-58.169345
4,4,2014,Winter,Albania,ALB,2.889100e+06,9808.0,0.000542,0,0.0,-0.006568,0.000000,0.000000,0.000000,41.000028,19.999962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,2014,Winter,India,IND,1.295600e+09,5458.0,0.000542,0,0.0,-0.012838,0.000000,0.000000,0.000000,22.351115,78.667743
70,70,2014,Winter,Ireland,IRL,4.657740e+06,52651.0,0.002167,0,0.0,0.015962,0.015962,4.692702,-4.692702,52.865196,-7.979460
71,71,2014,Winter,Peru,PER,3.009040e+07,11186.0,0.001355,0,0.0,-0.005085,0.000000,0.000000,0.000000,-6.869970,-75.045851
72,72,2014,Winter,Moldova,MDA,2.856950e+06,5739.0,0.001355,0,0.0,-0.007633,0.000000,0.000000,0.000000,47.287961,28.567094
73,73,2014,Winter,Nepal,NEP,2.690600e+07,2421.0,0.000271,0,0.0,-0.010521,0.000000,0.000000,0.000000,28.108393,84.091714

In [4]:
summer_ml_file.columns

Index(['Year', 'season', 'country', 'noc', 'population', 'gdpperc',
       'athlete_share', 'host', 'country_medal_total', 'medal_share_predicted',
       'positive_medal_share', 'predicted_medals',
       'Difference_Acutal_Predicted', 'latitude', 'longitude'],
      dtype='object')

In [5]:
winter_ml_file.columns

Index(['Unnamed: 0', 'year', 'season', 'Country', 'noc', 'population',
       'gdpperc', 'athlete_share', 'host', 'country_medal_total',
       'medal_share_predicted', 'positive_medal_share', 'predicted_medals',
       'Difference_Actual_Predicted', 'Latitude', 'Longitude'],
      dtype='object')

In [6]:
# merging two csv files
merged_df = pd.concat(
    map(pd.read_csv, ['summer_ML_final.csv', 'Winter_ML_final.csv']), ignore_index=True)
print(merged_df)

       Year  season       country  noc    population  gdpperc  athlete_share  \
0    2016.0  summer       Bolivia  BOL  1.103180e+07   6355.0       0.001225
1    2016.0  summer       Finland  FIN  5.495300e+06  37239.0       0.006430
2    2016.0  summer  South Africa  RSA  5.620760e+07  12139.0       0.010308
3    2016.0  summer      Dominica  DMA  7.130700e+04   9550.0       0.000204
4    2016.0  summer       Ukraine  UKR  4.500470e+07   9214.0       0.023576
..      ...     ...           ...  ...           ...      ...            ...
230     NaN  Winter           NaN  IND  1.295600e+09   5458.0       0.000542
231     NaN  Winter           NaN  IRL  4.657740e+06  52651.0       0.002167
232     NaN  Winter           NaN  PER  3.009040e+07  11186.0       0.001355
233     NaN  Winter           NaN  MDA  2.856950e+06   5739.0       0.001355
234     NaN  Winter           NaN  NEP  2.690600e+07   2421.0       0.000271

     host  country_medal_total  medal_share_predicted  ...  predicted_medals  \
0       0                  0.0              -0.002457  ...          0.000000
1       0                  1.0               0.003392  ...          3.246085
2       0                 10.0               0.011354  ...         10.865334
3       0                  0.0              -0.004325  ...          0.000000
4       0                 11.0               0.030684  ...         29.364808
..    ...                  ...                    ...  ...               ...
230     0                  0.0              -0.012838  ...          0.000000
231     0                  0.0               0.015962  ...          4.692702
232     0                  0.0              -0.005085  ...          0.000000
233     0                  0.0              -0.007633  ...          0.000000
234     0                  0.0              -0.010521  ...          0.000000

     Difference_Acutal_Predicted   latitude  longitude  Unnamed: 0    year  \
0                       0.000000 -17.056870 -64.991229         NaN     NaN
1                      -2.246085  63.246778  25.920916         NaN     NaN
2                      -0.865334 -28.816624  24.991639         NaN     NaN
3                       0.000000  19.097403 -70.302803         NaN     NaN
4                     -18.364808  49.487197  31.271832         NaN     NaN
..                           ...        ...        ...         ...     ...
230                          NaN        NaN        NaN        69.0  2014.0
231                          NaN        NaN        NaN        70.0  2014.0
232                          NaN        NaN        NaN        71.0  2014.0
233                          NaN        NaN        NaN        72.0  2014.0
234                          NaN        NaN        NaN        73.0  2014.0

     Country Difference_Actual_Predicted   Latitude  Longitude
0        NaN                         NaN        NaN        NaN
1        NaN                         NaN        NaN        NaN
2        NaN                         NaN        NaN        NaN
3        NaN                         NaN        NaN        NaN
4        NaN                         NaN        NaN        NaN
..       ...                         ...        ...        ...
230    India                    0.000000  22.351115  78.667743
231  Ireland                   -4.692702  52.865196  -7.979460
232     Peru                    0.000000  -6.869970 -75.045851
233  Moldova                    0.000000  47.287961  28.567094
234    Nepal                    0.000000  28.108393  84.091714

[235 rows x 21 columns]

In [7]:
merged_df.columns

Index(['Year', 'season', 'country', 'noc', 'population', 'gdpperc',
       'athlete_share', 'host', 'country_medal_total', 'medal_share_predicted',
       'positive_medal_share', 'predicted_medals',
       'Difference_Acutal_Predicted', 'latitude', 'longitude', 'Unnamed: 0',
       'year', 'Country', 'Difference_Actual_Predicted', 'Latitude',
       'Longitude'],
      dtype='object')

In [8]:
# Export df as a CSV
merged_df.to_csv('Merged_ML_files.csv', index=False)

In [9]:
# Convert Pandas Df to JSON
json_output = r"C:\Users\Lenovo\Documents\olympic_medal_analysis\Olympic_map\static\json\Merged_ML_files.json"
output = merged_df.to_json(json_output, indent = 1, orient= 'records')